### ISSUE TITLE
/vehicle garage error

### ISSUE THREAD

**Issue by RemcoPl** [relavis/VehiclesPlus#7] opened 2020-08-20 13:58 UTC
**Describe the bug**
if we do /vehicle garage then this error appers in our console
We want to test it on our test server but no luck so far

**To Reproduce**
1. download 1.16.1"
2. Setup a server with the plugin.
3. do /vehicle garage and the error apper

**Expected behavior**
/vehicle garage gui 

**Screenshots or Video Recordings**
Nope

**Server and Plugin Informations**
 - Installed plugins: 36 other plugins
 - VehiclesPlus Version: 2.0.6
 - Pro or Lite? Pro
 - Server Platform and Version [eg: **PaperSpigot** 1.16.1 #135]:
 - Operating System (if applicable):

**Additional context**
Add any other context about the problem here, server timings reports, React dump information, complete console log etc. Please do not make Pastebin dumps or screenshot expire.
[15:54:56 INFO]: RemcoPl issued server command: /vehicle garage
[15:54:56 INFO]: Loaded: 1 vehicles!
[15:54:56 INFO]: Loading ExampleCar
[15:54:56 INFO]: LEATHER_BOOTS
[15:54:56 INFO]: ExampleCar
[15:54:56 INFO]: [CommandLibrary] Something went wrong while invoking method 'openGarage' in class 'me.legofreak107.vehiclesplus.vehicles.commands.VehiclesCommand':
[15:54:56 WARN]: java.lang.reflect.InvocationTargetException
[15:54:56 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:54:56 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:54:56 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:54:56 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
[15:54:56 WARN]: at me.legofreak107.vehiclesplus.libraries.commandlibrary.objects.SubCommand.invokeMethod(SubCommand.java:68)
[15:54:56 WARN]: at me.legofreak107.vehiclesplus.libraries.commandlibrary.objects.SubCommand.invoke(SubCommand.java:59)
[15:54:56 WARN]: at me.legofreak107.vehiclesplus.libraries.commandlibrary.objects.LibraryCommandExecutor.onCommand(LibraryCommandExecutor.java:41)
[15:54:56 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[15:54:56 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[15:54:56 WARN]: at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794)
[15:54:56 WARN]: at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1910)
[15:54:56 WARN]: at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1721)
[15:54:56 WARN]: at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[15:54:56 WARN]: at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[15:54:56 WARN]: at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[15:54:56 WARN]: at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
[15:54:56 WARN]: at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[15:54:56 WARN]: at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[15:54:56 WARN]: at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[15:54:56 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1137)
[15:54:56 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1130)
[15:54:56 WARN]: at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[15:54:56 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1091)
[15:54:56 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1005)
[15:54:56 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[15:54:56 WARN]: at java.lang.Thread.run(Thread.java:748)
[15:54:56 WARN]: Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_12_R1/inventory/CraftItemStack
[15:54:56 WARN]: at me.legofreak107.vehiclesplus.vehicles.reflection.versions.NMSItemStack_1_12_2.setString(NMSItemStack_1_12_2.java:28)
[15:54:56 WARN]: at me.legofreak107.vehiclesplus.libraries.gui.objects.types.PaginationGui.<init>(PaginationGui.java:54)
[15:54:56 WARN]: at me.legofreak107.vehiclesplus.vehicles.commands.VehiclesCommand$1.<init>(VehiclesCommand.java:180)
[15:54:56 WARN]: at me.legofreak107.vehiclesplus.vehicles.commands.VehiclesCommand.openGarage(VehiclesCommand.java:180)
[15:54:56 WARN]: ... 26 more

**Comment by relavis** [comment] 2020-08-28 15:49
Duplicate of #4

**Closed by relavis** 2020-08-28 15:49 UTC
Labels: 1.16.x, Bug, Duplicate
