### ISSUE TITLE
Can't open Garage

### ISSUE THREAD

**Issue by G-K-G** [relavis/VehiclesPlus#14] opened 2020-08-28 02:10 UTC
When I do /v garage I get an error and it doesn't open
if you give yourself a vehicle it says you got it but as soon as you try to open the garage it doesn't work and spits out this error:
"Something went wrong while invoking method 'openGarage' in class 'me.legofreak107.vehiclesplus.vehicles.commands.VehiclesCommand':"

**To Reproduce**
1. /vehicle give user ExamplePlane 1 1 1
2. /vehicle garage
3. Go to console

**Expected behavior**
would have opened the garage

**Screenshots or Video Recordings**
https://prnt.sc/u77bwn

**Server and Plugin Informations**
 - Installed plugins: Dynmap, EssentialsX, EssentialsXChat, Factions, Harbor, LuckPerms, ProtocolLib, SuperVanish, TAB, UltraPunishments, Vault, VehiclesPlusPro, WorldBorder, WorldEdit
 - VehiclesPlus Version: Pro
 - PaperSpigot 1.16.2 #144

**Comment by relavis** [comment] 2020-08-28 15:49
Duplicate of #4

**Closed by relavis** 2020-08-28 15:49 UTC
Labels: 1.16.x, Bug, Duplicate, PaperSpigot
