### ISSUE TITLE
/v shop NPE

### ISSUE THREAD

**Issue by EIevenn** [relavis/VehiclesPlus#29] opened 2020-10-12 20:29 UTC
While doing any /v or /vehicle command it completely ignores it and brings an error to the console

To Reproduce

/vehicle shop 
/vehicle garage
Go to console
See error

Expected behavior:
Would have done the command.

Screenshots or Video Recordings
https://i.gyazo.com/9a4e369e3c52c34b120a3096226ff6c9.png

Server and Plugin Informations

Installed plugins: AAC, AdvancedArmorStands, AdvancedAuctionHouse, AdvancedBan, AltDetector, AntiWDL, BottledExp, ChairStairs, ChatControl, ClearLag, CombatTagPlus, CoreProtect, CraftEnhance, dynmap, Dynmap-Towny, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, ImageOnMap, InventoryRollback, Jobs, LuckPerms, MaintenanceSpigot, MessageAnnouncer, MeteorStorms, Multiverse-Core, Multiverse-Inventories, MyCommand, OpenInv, PacketLimiter, PerWorldInventory, PlaceholderAPI, PluginConstructorAPI, PlugMan, PowerlessLamps, PremiumVanish, ProtocolLib, SimpleRename, spark, StaffChat, Suffixes, TabList, Towny, TownyChat, TownyNameUpdater, TradeSystem, Vault, VehiclesPlusPro, ViaVersion, WorldEdit, WorldEditSelectionVisualizer, WorldGuard, WorldGuardExtraFlags
VehiclesPlus Version: Pro
PaperSpigot 1.12.2 #1618

**Comment by agapelogos4** [comment] 2020-10-13 04:27
I'm having a problem with the command /v garage and /v shop, the GUI will not show up. Minecraft Spigot server version 1.16.3 my other plugins are...
Command panels, AntiCurse, mcMMO, Citizens, SetTheSpawn, SetHome, ShipBukkit, MythicMobs, CitizensCMD, EssentialsXXMPP, EssentialsXSpawn, EssentialsXProtect, EssentialsGeoIP, EssentialsXChat, EssentialsXAntiBuild, EssentialsX MoneyHunters, FogusCore, ChestShop, PluginConstructorAPI, QualityArmory, ItemBridge, ProtocolLib, Light-API, PlaceholderAPI, SaberFactions, Vault, Worldedit, Multiverse and WorldGuard
VehiclesPlus Version: Pro

The error that comes up is... 
20:26:04 CommandLibrary: Something went wrong while invoking method 'openGarage' in class 'me.legofreak107.vehiclesplus.vehicles.commands.VehiclesCommand': 20:26:04 CONSOLE: thread/WARN]: java.lang.reflect.InvocationTargetException 20:26:04 CONSOLE: thread/WARN]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 20:26:04 CONSOLE: thread/WARN]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:26:04 CONSOLE: thread/WARN]: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:26:04 CONSOLE: thread/WARN]: at java.base/java.lang.reflect.Method.invoke(Method.java:566) 20:26:04 CONSOLE: thread/WARN]: at me.legofreak107.vehiclesplus.libraries.commandlibrary.objects.SubCommand.invokeMethod(SubCommand.java:68)
20:26:04 CONSOLE: thread/WARN]: at me.legofreak107.vehiclesplus.libraries.commandlibrary.objects.SubCommand.invoke(SubCommand.java:59)
20:26:04 CONSOLE: thread/WARN]: at me.legofreak107.vehiclesplus.libraries.commandlibrary.objects.LibraryCommandExecutor.onCommand(LibraryCommandExecutor.java:41)
20:26:04 CONSOLE: thread/WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) 20:26:04 CONSOLE: thread/WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
20:26:04 CONSOLE: thread/WARN]: at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:758)
20:26:04 CONSOLE: thread/WARN]: at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1697) 20:26:04 CONSOLE: thread/WARN]: at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1540)
20:26:04 CONSOLE: thread/WARN]: at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47)
20:26:04 CONSOLE: thread/WARN]: at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) 20:26:04 CONSOLE: thread/WARN]: at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
20:26:04 CONSOLE: thread/WARN]: at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18)
20:26:04 CONSOLE: thread/WARN]: at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144)
20:26:04 CONSOLE: thread/WARN]: at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
20:26:04 CONSOLE: thread/WARN]: at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118) 20:26:04 CONSOLE: thread/WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941)
20:26:04 CONSOLE: thread/WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934)
20:26:04 CONSOLE: thread/WARN]: at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeAll(SourceFile:103)
20:26:04 CONSOLE: thread/WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:917) 20:26:04 CONSOLE: thread/WARN]: at
net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850)
20:26:04 CONSOLE: thread/WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164)
20:26:05 CONSOLE: thread/WARN]: at java.base/java.lang.Thread.run(Thread.java:834)
20:26:05 CONSOLE: thread/WARN]: Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_12_R1/inventory/CraftItemStack
20:26:05 CONSOLE: thread/WARN]: at me.legofreak107.vehiclesplus.vehicles.reflection.versions.NMSItemStack_1_12_2.setString(NMSItemStack_1_12_2.java:28)
20:26:05 CONSOLE: thread/WARN]: at me.legofreak107.vehiclesplus.libraries.gui.objects.types.PaginationGui.<init>(PaginationGui.java:54)
20:26:05 CONSOLE: thread/WARN]: at me.legofreak107.vehiclesplus.vehicles.commands.VehiclesCommand$1.<init>(VehiclesCommand.java:151)
20:26:05 CONSOLE: thread/WARN]: at me.legofreak107.vehiclesplus.vehicles.commands.VehiclesCommand.openGarage(VehiclesCommand.java:151)
20:26:05 CONSOLE: thread/WARN]: ... 26 more

**Comment by agapelogos4** [comment] 2020-10-13 14:24
VehiclesPlus - Pro 2.0.4

I get this error in the consul after running the command /v shop

07:21:50 CommandLibrary: Something went wrong while invoking method 'shop' in class 'me.legofreak107.vehiclesplus.vehicles.commands.VehiclesCommand':
07:21:50 CONSOLE: thread/WARN]: java.lang.reflect.InvocationTargetException
07:21:50 CONSOLE: thread/WARN]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
07:21:50 CONSOLE: thread/WARN]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
07:21:50 CONSOLE: thread/WARN]: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
07:21:50 CONSOLE: thread/WARN]: at java.base/java.lang.reflect.Method.invoke(Method.java:566)
07:21:50 CONSOLE: thread/WARN]: at me.legofreak107.vehiclesplus.libraries.commandlibrary.objects.SubCommand.invokeMethod(SubCommand.java:68)
07:21:50 CONSOLE: thread/WARN]: at me.legofreak107.vehiclesplus.libraries.commandlibrary.objects.SubCommand.invoke(SubCommand.java:59)
07:21:50 CONSOLE: thread/WARN]: at me.legofreak107.vehiclesplus.libraries.commandlibrary.objects.LibraryCommandExecutor.onCommand(LibraryCommandExecutor.java:41)
07:21:50 CONSOLE: thread/WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
07:21:50 CONSOLE: thread/WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
07:21:50 CONSOLE: thread/WARN]: at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:758)
07:21:50 CONSOLE: thread/WARN]: at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1697)
07:21:50 CONSOLE: thread/WARN]: at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1540)
07:21:50 CONSOLE: thread/WARN]: at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47)
07:21:50 CONSOLE: thread/WARN]: at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
07:21:50 CONSOLE: thread/WARN]: at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
07:21:50 CONSOLE: thread/WARN]: at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18)
07:21:51 CONSOLE: thread/WARN]: at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144)
07:21:51 CONSOLE: thread/WARN]: at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
07:21:51 CONSOLE: thread/WARN]: at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118)
07:21:51 CONSOLE: thread/WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941)
07:21:51 CONSOLE: thread/WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934)
07:21:51 CONSOLE: thread/WARN]: at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(SourceFile:127)
07:21:51 CONSOLE: thread/WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:918)
07:21:51 CONSOLE: thread/WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850)
07:21:51 CONSOLE: thread/WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164)
07:21:51 CONSOLE: thread/WARN]: at java.base/java.lang.Thread.run(Thread.java:834)
07:21:51 CONSOLE: thread/WARN]: Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_12_R1/inventory/CraftItemStack
07:21:51 CONSOLE: thread/WARN]: at me.legofreak107.vehiclesplus.vehicles.reflection.versions.NMSItemStack_1_12_2.setString(NMSItemStack_1_12_2.java:28)
07:21:51 CONSOLE: thread/WARN]: at me.legofreak107.vehiclesplus.libraries.gui.objects.types.PaginationGui.<init>(PaginationGui.java:54)
07:21:51 CONSOLE: thread/WARN]: at me.legofreak107.vehiclesplus.vehicles.commands.VehiclesCommand$2.<init>(VehiclesCommand.java:224)
07:21:51 CONSOLE: thread/WARN]: at me.legofreak107.vehiclesplus.vehicles.commands.VehiclesCommand.shop(VehiclesCommand.java:224)
07:21:51 CONSOLE: thread/WARN]: ... 26 more
07:21:51 CONSOLE: thread/WARN]: Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_12_R1.inventory.CraftItemStack
07:21:51 CONSOLE: thread/WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
07:21:51 CONSOLE: thread/WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96)
07:21:51 CONSOLE: thread/WARN]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
07:21:51 CONSOLE: thread/WARN]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
07:21:51 CONSOLE: thread/WARN]: ... 30 more

**Comment by RPS1222** [comment] 2020-10-13 21:52
Relavis, this is a player from my server... I _did_ make a [GitHub request](https://github.com/relavis/VehiclesPlus/issues/24), where you told me to friend you. I tried contacting you with any information that you needed, but you never responded to me. This isn't okay to ignore me for so long and then tell me to do something that I've already done. I paid money for this plugin, which isn't working, and I want it fixed or I want my money back. I would understand if this was for the free version, but you aren't helping out your _paying_ customers.

**Comment by relavis** [comment] 2020-10-13 23:02
Fixed in 2.0.9-dev1

**Closed by relavis** 2020-10-13 23:02 UTC
Labels: 1.12.x, Bug
